DROP ALL OBJECTS DELETE FILES
CREATE MEMORY TABLE IF NOT EXISTS sample(id int PRIMARY KEY auto_increment, sample_id VARCHAR(16) NOT NULL, name VARCHAR(50), description VARCHAR(100), use_yn CHAR(1), reg_user VARCHAR(10))
CREATE MEMORY TABLE IF NOT EXISTS ids(id int PRIMARY KEY auto_increment, table_name VARCHAR(16) NOT NULL, seq int NOT NULL)
